// <auto-generated />
using System;
using DocumentaryManagementWebApi.DataLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DocumentaryManagementWebApi.DataLayer.Migrations
{
    [DbContext(typeof(DocumentaryDbContext))]
    [Migration("20210211153635_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocumentaryManagementWebApi.DataLayer.Models.ActorModel", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActorAge")
                        .HasColumnType("int");

                    b.Property<DateTime>("ActorDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActorGender")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("DocumentaryManagementWebApi.DataLayer.Models.DocumentaryModel", b =>
                {
                    b.Property<int>("DocumentaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentaryGenre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentaryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DocumentaryId");

                    b.HasIndex("ActorId");

                    b.ToTable("Docuemntaries");
                });

            modelBuilder.Entity("DocumentaryManagementWebApi.DataLayer.Models.DocumentaryModel", b =>
                {
                    b.HasOne("DocumentaryManagementWebApi.DataLayer.Models.ActorModel", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });
#pragma warning restore 612, 618
        }
    }
}
